---
  - name: update packages
    become: true
    apt:
      upgrade: dist
      update_cache: yes
  
  - name: Check for Python
    shell: "test -e {{ python_interpreter }}"
    changed_when: false
    failed_when: false
    register: check_python
  
  - name: "install python for Ansible."
    raw: apt -y update && apt install -y python-minimal
    when: check_python.rc != 0
  
  - name: "install dependencies."
    become: true
    apt:
      name: ["nodejs", "npm"]
      state: latest
  
  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present
