---
  - name: update packages
    become: true
    apt:
      upgrade: dist
      update_cache: yes

  - name: remove unused dependencies
    become: true
    apt:
      autoremove: true

  - name: "install python for Ansible."
    become: true
    apt:
      name: python3
      state: latest
      update_cache: yes
