---
  - name: create backend directory
    become: true
    path: ~/backend_dir
    state: directory

  - name: Copy artifact to instance
    become: true
    copy:
      src: ~/project/artifact.tar.gz
      dest: /home/ubuntu/backend_dir/artifact.tar.gz

  - name: extract and remove artifact
    become: true
    shell: |
      cd /home/ubuntu/backend_dir/
      tar xzvf artifact.tar.gz
      rm artifact.tar.gz

  - name: starting app
    become: true
    shell: |
      cd /home/ubuntu/backend_dir/
      npm install
      pm2 stop default
      pm2 start npm -- start
