---
  - name: "install dependencies."
    become: true
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: create backend directory
    file:
      path: /home/ubuntu/backend_dir
      state: directory

  - name: Copy artifact to instance
    copy:
      src: ~/project/artifact.tar.gz
      dest: /home/ubuntu/backend_dir/artifact.tar.gz

  - name: extract and remove artifact
    shell: |
      cd /home/ubuntu/backend_dir/
      tar xzvf artifact.tar.gz
      rm artifact.tar.gz

  - name: setup and start app
    shell: |
      cd /home/ubuntu/backend_dir/
      npm install
      npm run build
      pm2 stop "backend app"
      pm2 start npm --name "backend app" -- start
    register: start_server_result
    notify: show_start_server_output