version: 2.1
orbs:
  slack: circleci/slack@4.12.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend && \
            npm install && \
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend && \
            npm install && \
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: "Run frontend test"
          command: |
            cd frontend && \
            npm install && \
            npm run test

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: "Run backend test"
          command: |
            cd backend && \
            npm install && \
            npm run test

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: "Run frontend scan"
          command: |
            cd frontend && \
            npm install && \
            # npm install oauth-sign@^0.9.0
            npm audit --audit-level=critical
      - slack/notify:
          template: basic_fail_1
          event: fail
      - slack/notify:
          template: success_tagged_deploy_1
          event: pass

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: "Run backend scan"
          command: |
            cd backend && \
            npm install && \
            # npm install oauth-sign@^0.9.0
            npm audit fix --audit-level=critical
      - slack/notify:
          template: basic_fail_1
          event: fail

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
         requires:
           - build-frontend
      - test-backend:
         requires:
           - build-backend
      - scan-frontend:
         context: udacity-project3
         requires:
           - build-frontend
      - scan-backend:
         context: udacity-project3
         requires:
           - build-backend